# -*- coding: utf-8 -*-
"""data cleaniga .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15n4KUn__HONWJNW0IVHjLkWuzScorLyT
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/multi_touch_attribution_dataset.csv")

df = df.drop_duplicates()
df

df.isnull().sum()

print("Dataset Preview:")
print(df.head())

print("\nDataset Information:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nTotal Duplicate Rows:", df.duplicated().sum())

df = df.drop_duplicates()

df['customer_status'] = df['customer_status'].fillna('Not Converted')

df['converted'] = df['conversion_id'].notna().astype(int)

df['conversion_id'] = df['conversion_id'].fillna('No_Conversion')
df['conversion_timestamp_utc'] = df['conversion_timestamp_utc'].fillna('No_Conversion')

for column in df.select_dtypes(include='object').columns:
    df[column] = df[column].fillna('Unknown')

print("\nMissing Values After Cleaning:")
print(df.isnull().sum())

print("\nCleaned Dataset Preview:")
print(df.head())

df.to_csv('/content/multi_touch_attribution_dataset_cleaned.csv', index=False)

print("\nCleaned dataset saved successfully!")
